# Generated by Django 3.0.5 on 2020-04-29 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=60)),
                ('length', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
