# Generated by Django 3.0.5 on 2020-04-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20200429_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='gender',
            field=models.CharField(choices=[('F', 'female'), ('M', 'male')], max_length=1),
        ),
    ]
