# Generated by Django 3.0.5 on 2020-08-16 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='cost',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
    ]
