# Generated by Django 3.0.5 on 2020-08-17 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_cost_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cost',
            old_name='cost',
            new_name='amount',
        ),
    ]
