# Generated by Django 3.0.5 on 2020-08-09 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('kind', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(upload_to='media/')),
                ('state', models.CharField(choices=[('F', 'free'), ('R', 'reserved'), ('C', 'confirmed')], max_length=1)),
            ],
        ),
    ]
