# Generated by Django 3.0.5 on 2020-08-10 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_borrower'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='price',
            field=models.IntegerField(default=1000),
        ),
    ]
